version: '3.2'

services:
  php:
    container_name: igraal_php
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: ./api
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
    depends_on:
      - db-igraal
    env_file:
      - ./api/.env
    # Comment out these volumes in production
    volumes:
      - ./api:/srv/api:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw

  api:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    build:
      context: ./api
      dockerfile: Dockerfile.nginx
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/nginx
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
    ports:
      - "8080:80"

  cache-proxy:
    image: ${CONTAINER_REGISTRY_BASE}/varnish
    build:
      context: ./api
      dockerfile: Dockerfile.varnish
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - api
    # Comment out this volume in production
    volumes:
      - ./api/docker/varnish/conf:/etc/varnish:ro
    ports:
      - "8081:80"
  db-igraal:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: igraal
      MYSQL_USER: igraal
      MYSQL_PASSWORD: igraal
    ports:
      - "3306:3306"

  admin:
    image: ${CONTAINER_REGISTRY_BASE}/admin
    build:
      context: ./admin
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/admin
    env_file:
      - ./admin/.env
    volumes:
      - ./admin:/usr/src/admin:rw,cached
      - /usr/src/admin/node_modules
    ports:
      - "81:3000"

  h2-proxy:
    # Don't use this proxy in prod
    build:
      context: ./h2-proxy
    depends_on:
      - admin
      - api
      - cache-proxy
    ports:
      - "443:443"
      - "444:444"
      - "8443:8443"
      - "8444:8444"
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
  rabbitmq:
    image: rabbitmq:3.6.9-management-alpine
    restart: always
    env_file: api/.env
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
