old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        event:
            connection:       default
            exchange_options: { name: 'event', type: fanout }
    consumers:
        event:
            connection:       default
            exchange_options: { name: 'event', type: fanout }
            queue_options:    { name: 'event'}
            callback:         App\Queue\Consumer\RabbitMqConsumer
            enable_logger:    true
services:
    OldSound\RabbitMqBundle\RabbitMq\ProducerInterface: "@old_sound_rabbit_mq.event_producer"

    App\Queue\Producer\ProducerInterface: "@app.queue.producer"
